//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADAA.Resources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board of directors.
        /// </summary>
        public static string BoardName {
            get {
                return ResourceManager.GetString("BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string DirectorEmail {
            get {
                return ResourceManager.GetString("DirectorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor Michail I. Aghajanov, MD. President.
        /// </summary>
        public static string DirectorName1 {
            get {
                return ResourceManager.GetString("DirectorName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovhannes M. Manvelyan, Professor, MD, Ph.D..
        /// </summary>
        public static string DirectorName2 {
            get {
                return ResourceManager.GetString("DirectorName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artashes G. Gevorgyan, Ph.D..
        /// </summary>
        public static string DirectorName3 {
            get {
                return ResourceManager.GetString("DirectorName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jane L. Mahakian, Ph.D..
        /// </summary>
        public static string DirectorName4 {
            get {
                return ResourceManager.GetString("DirectorName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string DirectorPhone {
            get {
                return ResourceManager.GetString("DirectorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President.
        /// </summary>
        public static string DirectorPosition1 {
            get {
                return ResourceManager.GetString("DirectorPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice-president in clinical work.
        /// </summary>
        public static string DirectorPosition2 {
            get {
                return ResourceManager.GetString("DirectorPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary.
        /// </summary>
        public static string DirectorPosition3 {
            get {
                return ResourceManager.GetString("DirectorPosition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of ADAA USA.
        /// </summary>
        public static string DirectorPosition4 {
            get {
                return ResourceManager.GetString("DirectorPosition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To study social and medical and biologic aspects of Alzheimer’s disease both in Republic Armenia, and behind its limits..
        /// </summary>
        public static string ListItem1 {
            get {
                return ResourceManager.GetString("ListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To promote distribution of modern representations about essence, risk factors, and the reasons of occurrence and existing methods of treatment of Alzheimer’s disease..
        /// </summary>
        public static string ListItem2 {
            get {
                return ResourceManager.GetString("ListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To support the scientific directions directed on a deepening of our understanding of essence of Alzheimer’s disease..
        /// </summary>
        public static string ListItem3 {
            get {
                return ResourceManager.GetString("ListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To improve quality of a life of patients with dementia and their trustees..
        /// </summary>
        public static string ListItem4 {
            get {
                return ResourceManager.GetString("ListItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To lower psychological loading on trustees in families..
        /// </summary>
        public static string ListItem5 {
            get {
                return ResourceManager.GetString("ListItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagation of bases of mental health and, first of all, to teach patients to overcome the fear, silence and shame for the illness..
        /// </summary>
        public static string ListItem6 {
            get {
                return ResourceManager.GetString("ListItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase of public knowledge in Armenia and Diaspora..
        /// </summary>
        public static string ListItem7 {
            get {
                return ResourceManager.GetString("ListItem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stimulate interaction between experts of a various structure within the framework of Association..
        /// </summary>
        public static string ListItem8 {
            get {
                return ResourceManager.GetString("ListItem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Armenian Association of Alzheimer’s Disease (ADAA) was founded in 2002 by Dr. Michail I. Aghajanov..
        /// </summary>
        public static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On March 2010, at the International Conference of Alzheimer’s Disease International  in Tsessaloniki, Greece, the ADAA was recognized as a full member of Alzheimer’s Disease International, an International federation of 76 Alzheimer’s associations around the world..
        /// </summary>
        public static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of the Alzheimer’s Disease Armenian Association (ADAA).
        /// </summary>
        public static string Paragraph4 {
            get {
                return ResourceManager.GetString("Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
