//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADAA.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss of memory,.
        /// </summary>
        public static string AlzheimerListItem1 {
            get {
                return ResourceManager.GetString("AlzheimerListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulties in a presence of correct words or in understanding of that other people speak,.
        /// </summary>
        public static string AlzheimerListItem2 {
            get {
                return ResourceManager.GetString("AlzheimerListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulties in performance routine has put,.
        /// </summary>
        public static string AlzheimerListItem3 {
            get {
                return ResourceManager.GetString("AlzheimerListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in mood and personal qualities..
        /// </summary>
        public static string AlzheimerListItem4 {
            get {
                return ResourceManager.GetString("AlzheimerListItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mision is:.
        /// </summary>
        public static string MissionListHead {
            get {
                return ResourceManager.GetString("MissionListHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informing about деменции, in particular about Alzheimer&apos;s disease,.
        /// </summary>
        public static string MissionListItem1 {
            get {
                return ResourceManager.GetString("MissionListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informing about Armenian Associations of Alzheimer&apos;s disease,.
        /// </summary>
        public static string MissionListItem2 {
            get {
                return ResourceManager.GetString("MissionListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To promote patients with деменцией, to their families and trustees..
        /// </summary>
        public static string MissionListItem3 {
            get {
                return ResourceManager.GetString("MissionListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Alzheimer&apos;s disease?.
        /// </summary>
        public static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alzheimer&apos;s disease for the first time has been described in 1906 by German neuropathologist Alois Altsgejmer.
        ///        Alzheimer&apos;s disease is the most widespread reason of dementia. Under the term &quot;dementia&quot; various progressing degenerative
        ///        brain syndromes which amaze memory, thinking, behavior and emotions are incorporated. Characteristic for dementia is:.
        /// </summary>
        public static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dementia is not a normal component of ageing. It does not know neither social, nor economic, ethnic or geographical borders.
        ///        Usually it is shown after 40-50 years, but earlier display of disease has been registered in 28 years. Though at each person
        ///        it is in own way shown dementia, however all these patients are not capable to care of themselves and require the everyday constant help..
        /// </summary>
        public static string Paragraph3 {
            get {
                return ResourceManager.GetString("Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For diagnostics of Alzheimer&apos;s disease while there is no test with which help probably correctly to diagnose. Therefore the doctor should
        ///        exclude all those diseases which result in development of dementia symptoms. Especially those diseases which are exposed to treatment:
        ///        infections, traumas, tumors, mental infringements. Even at exception of other diseases diagnostics of Alzheimer&apos;s disease remains suspected.
        ///        Authentic diagnostics is possible only microscopic research which is us [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Paragraph4 {
            get {
                return ResourceManager.GetString("Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alzheimer&apos;s disease is intensively studied all over the world, however will pass a lot of time before its final treatment will be found.
        ///        Therefore patients with dementia and their trustees require the constant practical help and support..
        /// </summary>
        public static string Paragraph5 {
            get {
                return ResourceManager.GetString("Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today more than 35 million people worldwide have dementia and those numbers will double every 20 years to 65,7 million in 2030 and 115,4
        ///        million in 2050, according to the World Alzheimer’s Report from Alzheimer’s Disease International..
        /// </summary>
        public static string Paragraph6 {
            get {
                return ResourceManager.GetString("Paragraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the international statistics in Armenia it should be totaled approximately 30 thousand patients with dementia..
        /// </summary>
        public static string Paragraph7 {
            get {
                return ResourceManager.GetString("Paragraph7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SloganBig {
            get {
                return ResourceManager.GetString("SloganBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SloganSmall {
            get {
                return ResourceManager.GetString("SloganSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
