//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Membership {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Membership() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADAA.Resources.Membership", typeof(Membership).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileges a professional member:.
        /// </summary>
        public static string Membership1Advantages {
            get {
                return ResourceManager.GetString("Membership1Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the right to elect and be elected,.
        /// </summary>
        public static string Membership1Adventage1 {
            get {
                return ResourceManager.GetString("Membership1Adventage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can visit on a regular basis assemblies and presentations of the organization,.
        /// </summary>
        public static string Membership1Adventage2 {
            get {
                return ResourceManager.GetString("Membership1Adventage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can visit conferences sponsored by the organization on preferential payments,.
        /// </summary>
        public static string Membership1Adventage3 {
            get {
                return ResourceManager.GetString("Membership1Adventage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receives reports of assemblies and other messages,.
        /// </summary>
        public static string Membership1Adventage4 {
            get {
                return ResourceManager.GetString("Membership1Adventage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the right to be elected in the board of ADAA..
        /// </summary>
        public static string Membership1Adventage5 {
            get {
                return ResourceManager.GetString("Membership1Adventage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional member can become the doctor, the researcher, the licensed psychologist or other professionals having corresponding formation.
        ///                The professional member gives a significant part of time to research in the field of Alzheimer’s disease. This work is directed on studying
        ///                of interrelation between function of a brain and behavior. The professional member works for improvement of quality of a life of people and
        ///                observes thus the maximum ethical standar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Membership1Description {
            get {
                return ResourceManager.GetString("Membership1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly fee: 5000AMD.
        /// </summary>
        public static string Membership1Fee {
            get {
                return ResourceManager.GetString("Membership1Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Member.
        /// </summary>
        public static string Membership1Title {
            get {
                return ResourceManager.GetString("Membership1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileges the caregivers / the member of family:.
        /// </summary>
        public static string Membership2Advantages {
            get {
                return ResourceManager.GetString("Membership2Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can visit on a regular basis assemblies and presentations of the organization,.
        /// </summary>
        public static string Membership2Adventage1 {
            get {
                return ResourceManager.GetString("Membership2Adventage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can visit conferences sponsored by the organization on preferential payments,.
        /// </summary>
        public static string Membership2Adventage2 {
            get {
                return ResourceManager.GetString("Membership2Adventage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receives reports of assemblies and other messages,.
        /// </summary>
        public static string Membership2Adventage3 {
            get {
                return ResourceManager.GetString("Membership2Adventage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice an year can receive distributed АDАА bulletins and books..
        /// </summary>
        public static string Membership2Adventage4 {
            get {
                return ResourceManager.GetString("Membership2Adventage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly fee: 2500AMD.
        /// </summary>
        public static string Membership2Fee {
            get {
                return ResourceManager.GetString("Membership2Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caregiver/the member of family.
        /// </summary>
        public static string Membership2Title {
            get {
                return ResourceManager.GetString("Membership2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileges of students - member’s АDАА:.
        /// </summary>
        public static string Membership3Advantages {
            get {
                return ResourceManager.GetString("Membership3Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can visit on a regular basis assemblies and presentations of the organization,.
        /// </summary>
        public static string Membership3Adventage1 {
            get {
                return ResourceManager.GetString("Membership3Adventage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can visit conferences sponsored by the organization on preferential payments,.
        /// </summary>
        public static string Membership3Adventage2 {
            get {
                return ResourceManager.GetString("Membership3Adventage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receives reports of assemblies and other messages,.
        /// </summary>
        public static string Membership3Adventage3 {
            get {
                return ResourceManager.GetString("Membership3Adventage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the right to be elected in the board of ADAA,.
        /// </summary>
        public static string Membership3Adventage4 {
            get {
                return ResourceManager.GetString("Membership3Adventage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receives the certificate of member АААD..
        /// </summary>
        public static string Membership3Adventage5 {
            get {
                return ResourceManager.GetString("Membership3Adventage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of Association as the student can be any person interested in problem Alzheimer who is graduated,
        ///                the post-graduate student or the student on medicine, psychology and other similar areas of a science..
        /// </summary>
        public static string Membership3Description {
            get {
                return ResourceManager.GetString("Membership3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly fee: 1000AMD.
        /// </summary>
        public static string Membership3Fee {
            get {
                return ResourceManager.GetString("Membership3Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of Association - the Student.
        /// </summary>
        public static string Membership3Title {
            get {
                return ResourceManager.GetString("Membership3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category concerns to persons, who needs only reception of messages on assemblies AAAD and other information.
        ///                They have not the right to choose or have office, or to receive discounts on sponsored by the organizations of conferences..
        /// </summary>
        public static string Membership4Description {
            get {
                return ResourceManager.GetString("Membership4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly fee: 2000AMD.
        /// </summary>
        public static string Membership4Fee {
            get {
                return ResourceManager.GetString("Membership4Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only reception of mail.
        /// </summary>
        public static string Membership4Title {
            get {
                return ResourceManager.GetString("Membership4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To have access all our serivces you can join us!.
        /// </summary>
        public static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership types.
        /// </summary>
        public static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
