//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Service {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Service() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADAA.Resources.Service", typeof(Service).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation and the organization of medical aid. We have “Center of infringement of memory”
        ///            which is in Yerevan in the  Muratsan University clinic (address: Muratsan str. 114). The purpose
        ///            of the center is improvement of the quality of  life of patients with dementia  and their caregivers.
        ///            This center has an opportunity to diagnose dementia, in particular Alzheimer’s disease,  consultations
        ///            of the patient and their necessary treatment. In the center the t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderedList1 {
            get {
                return ResourceManager.GetString("OrderedList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-site:.
        /// </summary>
        public static string OrderedList10 {
            get {
                return ResourceManager.GetString("OrderedList10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical researches. Clinical and epidemiological researches of mental frustration at aged people in Armenia..
        /// </summary>
        public static string OrderedList11 {
            get {
                return ResourceManager.GetString("OrderedList11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups of support: we have educational groups in Yerevan..
        /// </summary>
        public static string OrderedList2 {
            get {
                return ResourceManager.GetString("OrderedList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information service: our office is in Yerevan. We provide telephone consultations on places and telephone
        ///            consultation for the members of family requiring for the information and advice..
        /// </summary>
        public static string OrderedList3 {
            get {
                return ResourceManager.GetString("OrderedList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochures / booklets: we prepare printed materials for patients and caregivers in Armenian,
        ///            English and Russian languages..
        /// </summary>
        public static string OrderedList4 {
            get {
                return ResourceManager.GetString("OrderedList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bulletin and books: Twice an year we distribute bulletin and books among members of the organization..
        /// </summary>
        public static string OrderedList5 {
            get {
                return ResourceManager.GetString("OrderedList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training and training: we train caregivers, experts in the field of public health services..
        /// </summary>
        public static string OrderedList6 {
            get {
                return ResourceManager.GetString("OrderedList6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The companies in MASSMEDIA and on TV..
        /// </summary>
        public static string OrderedList7 {
            get {
                return ResourceManager.GetString("OrderedList7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The telephone line for the help in Yerevan:.
        /// </summary>
        public static string OrderedList8 {
            get {
                return ResourceManager.GetString("OrderedList8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity on International Alzheimer&apos;s  Day..
        /// </summary>
        public static string OrderedList9 {
            get {
                return ResourceManager.GetString("OrderedList9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find support from us. We offer next services:.
        /// </summary>
        public static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs on TV and radio,.
        /// </summary>
        public static string UnorderedList1 {
            get {
                return ResourceManager.GetString("UnorderedList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview in newspapers,.
        /// </summary>
        public static string UnorderedList2 {
            get {
                return ResourceManager.GetString("UnorderedList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochures and bulletin,.
        /// </summary>
        public static string UnorderedList3 {
            get {
                return ResourceManager.GetString("UnorderedList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A display of paintings,.
        /// </summary>
        public static string UnorderedList4 {
            get {
                return ResourceManager.GetString("UnorderedList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program of training..
        /// </summary>
        public static string UnorderedList5 {
            get {
                return ResourceManager.GetString("UnorderedList5", resourceCulture);
            }
        }
    }
}
